{% set name = "pydpc" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pydpc-{{ version }}.tar.gz
  sha256: f9a81a8d9b228d37fcce9f3b7a58e27c6efc9020b77ee5fa8f87367946e6aa2b

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - numpy >=1.7
    - cython >=0.20
    - setuptools >=0.6
    - pip
  run:
    - numpy >=2
    - python
    - matplotlib-base

test:
  imports:
    - pydpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cwehmeyer/pydpc
  summary: Python package for Density Peak-based Clustering
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
