{% set name = "pydpc" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pydpc-{{ version }}.tar.gz
  sha256: 18881e2f1a1ccd941b06bf2131ca7fe630b47db11d28a4b16886df9ca603afd4
  patches:
    - python312.patch

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - numpy >=1.7
    - cython >=0.20
    - setuptools >=0.6
    - pip
  run:
    - python
    - matplotlib-base
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - pydpc
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/cwehmeyer/pydpc
  summary: Python package for Density Peak-based Clustering
  license: LGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
